[package]
name = "kraznac"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "*"
terminal_size = "*"
rand = "*"
anyhow = "*"
crossterm = "*"
num-traits = "*"
num-derive = "*"
noise = "*"